version: "3"

services:
  reverse-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}--nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static-data:/backend/staticfiles
    depends_on:
      - django-api
      - angular-apache2

  angular-apache2:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}--angular
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist/frontend:/var/www/html/dist

  django-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}--django
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - static-data:/backend/staticfiles
    environment:
      - STATIC_ROOT=/backend/staticfiles

volumes:
  static-data:
